MAIN_MENU, PROFILE, SEARCH, REGISTER, CHOOSE, GET_NAME, GET_AGE, GET_SEX, GET_CITY, GET_PHOTO, GET_ABOUT, EDIT_PROFILE, EDIT_NAME, EDIT_AGE, EDIT_SEX, EDIT_CITY, EDIT_PHOTO, EDIT_ABOUT, SELECT_SEX_FILTER, SWIPE_MODE, GET_SEARCH_SEX, EDIT_SEARCH_SEX, LIKES_QUEUE = range(23)



